name: EAS Update on Push

on:
  push:
    branches: [main]
    paths:
      - 'apps/mobile/**'
  pull_request:
    branches: [main]
    paths:
      - 'apps/mobile/**'

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/mobile
    
    steps:
      - name: Check for EXPO_TOKEN
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: './apps/mobile/package-lock.json'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Create preview (PR)
        if: github.event_name == 'pull_request'
        run: |
          eas update --auto --branch=pr-${{ github.event.number }}
          echo "🚀 Preview deployment created for PR #${{ github.event.number }}"
          echo "Download Expo Go and scan QR code to test changes"

      - name: Create production update (Push to main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          eas update --auto --branch=production
          echo "✅ Production update published!"
          echo "Users with the app will receive this update automatically"
